### ISSUE TITLE
mullvad-vpn-bin

### ISSUE THREAD

**Issue by TheMainMMan** [xarblu/xarblu-overlay#138]
Hi, 
when I start the app it says "Connecting to Mullvad system service ..." and it just stays like that.
What kind of service is needed ?

I'm using OpenVPN and it works fine, but can't figure out how to use the app.
It has the same problem whether OpenVPN is running or not.

**Comment by xarblu** [comment]
That would be `mullvad-daemon.service` for systemd. There currently is no init script for openrc because I've never written one of those (never used openrc) and Mullvad doesn't supply one.  
The systemd service is located at `/usr/lib/systemd/system/mullvad-daemon.service`.  
Looking at it an init script would mainly just need to set `MULLVAD_RESOURCE_DIR="/opt/Mullvad VPN/resources/"` and then execute `/usr/bin/mullvad-daemon -v --disable-stdout-timestamps`.

**Comment by TheMainMMan** [comment]
I see, well I tried and it has some errors, no clue what those errors are.
I stopped OpenVPN before trying.

Found [this ](https://aur.archlinux.org/packages/mullvad-vpn-openrc)rc files in the Arch AUR, no luck with that either.

```
# /usr/bin/mullvad-daemon -v --disable-stdout-timestamps                                                                                                                                                                                ─╯
[mullvad_daemon::version][INFO] Starting mullvad-daemon - 2023.3 2023-04-05
[mullvad_daemon][INFO] Logging to /var/log/mullvad-vpn
[mullvad_daemon::rpc_uniqueness_check][DEBUG] Failed to locate/connect to another daemon instance, assuming there isn't one
[mullvad_daemon][INFO] Management interface listening on /var/run/mullvad-vpn
[mullvad_api::address_cache][DEBUG] Loading API addresses from /var/cache/mullvad-vpn/api-ip-address.txt
[mullvad_api::address_cache][DEBUG] Using API address: 45.83.223.196:443
[mullvad_api::availability][DEBUG] Suspending API requests
[mullvad_daemon::settings][INFO] Loading settings from /etc/mullvad-vpn/settings.json
[mullvad_daemon::settings][INFO] No settings were found. Using defaults.
[mullvad_daemon::settings][DEBUG] Writing settings to /etc/mullvad-vpn/settings.json
[mullvad_daemon::version_check][DEBUG] Loading version check cache from /var/cache/mullvad-vpn/version-info.json
[mullvad_daemon::version_check][WARN] Error: Unable to load cached version info
Caused by: Failed to open app version cache file for reading
Caused by: No such file or directory (os error 2)
[mullvad_relay_selector][DEBUG] Reading relays from /var/cache/mullvad-vpn/relays.json
[mullvad_relay_selector][DEBUG] Reading relays from /usr/bin/relays.json
[mullvad_relay_selector][ERROR] Failed to load bundled relays: Failed to open relay cache file
[mullvad_relay_selector][ERROR] Error: Unable to load cached relays
Caused by: Failed to open relay cache file
Caused by: No such file or directory (os error 2)
[mullvad_relay_selector][INFO] Initialized with 0 cached relays from 1970-01-01 01:00:00.000
[mullvad_api::availability][DEBUG] Pausing background API requests
[mullvad_daemon::account_history][INFO] Opening account history file in /etc/mullvad-vpn/account-history.json
[mullvad_daemon::target_state][DEBUG] No cached target state to load
[mullvad_daemon::device][DEBUG] Account manager has stopped
[mullvad_daemon][ERROR] Error: Unable to initialize daemon
Caused by: Tunnel state machine error
Caused by: Failed to initialize the route manager
Caused by: Internal route manager error
Caused by: Netlink error
Caused by: Received a netlink error message Operation not supported (os error 95)
[mullvad_daemon][DEBUG] Process exiting with code 1

```

**Comment by TheMainMMan** [comment]
I guess it probably needs Wireguard to be configured and enabled (not having it configured atm)  
I'm not sure about that though but will try that later.

I guess you have that setup.

**Comment by xarblu** [comment]
> ```
> # /usr/bin/mullvad-daemon -v --disable-stdout-timestamps                                                                                                                                                                                ─╯
> [mullvad_daemon::version][INFO] Starting mullvad-daemon - 2023.3 2023-04-05
> [mullvad_daemon][INFO] Logging to /var/log/mullvad-vpn
> [mullvad_daemon::rpc_uniqueness_check][DEBUG] Failed to locate/connect to another daemon instance, assuming there isn't one
> [mullvad_daemon][INFO] Management interface listening on /var/run/mullvad-vpn
> [mullvad_api::address_cache][DEBUG] Loading API addresses from /var/cache/mullvad-vpn/api-ip-address.txt
> [mullvad_api::address_cache][DEBUG] Using API address: 45.83.223.196:443
> [mullvad_api::availability][DEBUG] Suspending API requests
> [mullvad_daemon::settings][INFO] Loading settings from /etc/mullvad-vpn/settings.json
> [mullvad_daemon::settings][INFO] No settings were found. Using defaults.
> [mullvad_daemon::settings][DEBUG] Writing settings to /etc/mullvad-vpn/settings.json
> [mullvad_daemon::version_check][DEBUG] Loading version check cache from /var/cache/mullvad-vpn/version-info.json
> [mullvad_daemon::version_check][WARN] Error: Unable to load cached version info
> Caused by: Failed to open app version cache file for reading
> Caused by: No such file or directory (os error 2)
> [mullvad_relay_selector][DEBUG] Reading relays from /var/cache/mullvad-vpn/relays.json
> [mullvad_relay_selector][DEBUG] Reading relays from /usr/bin/relays.json
> [mullvad_relay_selector][ERROR] Failed to load bundled relays: Failed to open relay cache file
> [mullvad_relay_selector][ERROR] Error: Unable to load cached relays
> Caused by: Failed to open relay cache file
> Caused by: No such file or directory (os error 2)
> [mullvad_relay_selector][INFO] Initialized with 0 cached relays from 1970-01-01 01:00:00.000
> [mullvad_api::availability][DEBUG] Pausing background API requests
> [mullvad_daemon::account_history][INFO] Opening account history file in /etc/mullvad-vpn/account-history.json
> [mullvad_daemon::target_state][DEBUG] No cached target state to load
> [mullvad_daemon::device][DEBUG] Account manager has stopped
> [mullvad_daemon][ERROR] Error: Unable to initialize daemon
> Caused by: Tunnel state machine error
> Caused by: Failed to initialize the route manager
> Caused by: Internal route manager error
> Caused by: Netlink error
> Caused by: Received a netlink error message Operation not supported (os error 95)
> [mullvad_daemon][DEBUG] Process exiting with code 1
> ```

Did you maybe forget setting the environment variable? E.g:
```
# sudo MULLVAD_RESOURCE_DIR="/opt/Mullvad VPN/resources/" /usr/bin/mullvad-daemon -v --disable-stdout-timestamps
```

Also thanks for linking the AUR rc files. Might just add those to the ebuild.

**Comment by TheMainMMan** [comment]
Yeah, I did, but I've copied relays.json manually and it was the same error as what I'm pasting below
It's the lack of Wireguard options in the kernel 99.5%, I'll do that later today.

```
[mullvad_daemon::version][INFO] Starting mullvad-daemon - 2023.3 2023-04-05
[mullvad_daemon][INFO] Logging to /var/log/mullvad-vpn
[mullvad_daemon::rpc_uniqueness_check][DEBUG] Failed to locate/connect to another daemon instance, assuming there isn't one
[mullvad_daemon][INFO] Management interface listening on /var/run/mullvad-vpn
[mullvad_api::address_cache][DEBUG] Loading API addresses from /var/cache/mullvad-vpn/api-ip-address.txt
[mullvad_api::address_cache][DEBUG] Using API address: 45.83.223.196:443
[mullvad_api::availability][DEBUG] Suspending API requests
[mullvad_daemon::settings][INFO] Loading settings from /etc/mullvad-vpn/settings.json
[mullvad_daemon::version_check][DEBUG] Loading version check cache from /var/cache/mullvad-vpn/version-info.json
[mullvad_daemon::version_check][WARN] Error: Unable to load cached version info
Caused by: Failed to open app version cache file for reading
Caused by: No such file or directory (os error 2)
[mullvad_relay_selector][DEBUG] Reading relays from /var/cache/mullvad-vpn/relays.json
[mullvad_relay_selector][DEBUG] Reading relays from /opt/Mullvad VPN/resources/relays.json
[mullvad_relay_selector][INFO] Initialized with 700 cached relays from 2023-06-24 14:29:04.027
[mullvad_api::availability][DEBUG] Pausing background API requests
[mullvad_daemon::account_history][INFO] Opening account history file in /etc/mullvad-vpn/account-history.json
[mullvad_daemon::target_state][DEBUG] No cached target state to load
[mullvad_daemon][ERROR] Error: Unable to initialize daemon
Caused by: Tunnel state machine error
Caused by: Failed to initialize the route manager
Caused by: Internal route manager error
Caused by: Netlink error
Caused by: Received a netlink error message Operation not supported (os error 95)
[mullvad_daemon][DEBUG] Process exiting with code 1
[mullvad_daemon::device][DEBUG] Account manager has stopped
```

You're welcome, they look good, but in my case it's the kernel most likely, so I'll let you know.

**Comment by xarblu** [comment]
Added the rc scripts and some kernel config checks in 13c51f5.

**Comment by TheMainMMan** [comment]
I did follow the Wireguard Gentoo Wiki, there's actually only one option to enable in the kernel.
Also I emerged wireguard-tools, still getting the same error when I launch the app

I have no prior experience with Wireguard, on Mullvad website I created config files for Wireguard, getting this error :
```
# wg-quick up wg0                                                                                                                                                                                                                       ─╯
[#] ip link add wg0 type wireguard
[#] wg setconf wg0 /dev/fd/63
[#] ip -4 address add 192.168.1.16/24 dev wg0
[#] ip link set mtu 1420 up dev wg0
[#] resolvconf -a wg0 -m 0 -x
[#] wg set wg0 fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0 table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
RTNETLINK answers: Operation not supported
[#] resolvconf -d wg0 -f
[#] ip link delete dev wg0

```

Again, using OpenVPN but without app works, I'm not sure what's up with Wireguard.
App would be convenient because of the app exclusions and tunneling.
But otherwise I don't actually need it.

You don't actually use this app ?

**Comment by xarblu** [comment]
Hmm, for me the app works without any issues.

**Comment by TheMainMMan** [comment]
Okay, thanks, had to ask.

It works now, had to install gentoo-kernel-bin, I guess I'm missing some firewall options in the kernel or something.
IProute or IPtunnel maybe, not sure.
I'll try to figure it out.

Thanks for making this ebuild and for quick replies :+1: 

![m1](https://github.com/xarblu/xarblu-overlay/assets/11412353/7ca375c9-516d-48a6-be72-10e9b7d2ada2)
![m2](https://github.com/xarblu/xarblu-overlay/assets/11412353/05d5618e-9ba3-4e8e-8585-e936fd8fc746)
