### ISSUE TITLE
Stable Versions of LLVM Marked as Unstable?

### ISSUE THREAD

**Issue by acjones8** [xarblu/xarblu-overlay#251]
I noticed that the LLVM versions are marked as unstable in the KEYWORDS section, even when the same version in the Gentoo base repo is marked as stable. For example, LLVM 16.0.6 has the ~amd64 and ~x86 flags set in the xarblu repo, but in the Gentoo base repo, it's just amd64 and x86.

I was wondering if it might be possible to mirror the stable / unstable pattern from the base repo? As someone who runs unstable combined with ccache (to reduce unnecessary recompilation, saving both time and energy), it's really helpful to keep GCC and Clang (and their accompanying dependencies) held back at stable, to minimize how often the cache gets busted. Because LLVM is marked as unstable, portage doesn't want to install it, even though it seems to be the same as the upstream version save for the addition of the polly framework.

**Comment by xarblu** [comment]
Hm, I always thought 3rd party overlays weren't allowed to stabilise packages so I kept them as `~arch`.
But now that I tried looking for a source for that in the Gentoo docs I can't find it.
All they say is to [have the architecture teams do stabilisation](https://devmanual.gentoo.org/keywording/index.html#moving-from-arch-to-arch) which is done for `sys-devel/llvm::gentoo`...

...I guess it would be fine to mirror the stabilisation pattern from `::gentoo` in that case. As you said, they are already mirrored besides the addition of the opt-in `polly` flag so might as well mirror `KEYWORDS`.
