### ISSUE TITLE
media-libs/svt-av1-1.8.0: filesize does not match recorded size

### ISSUE THREAD

**Issue by Gaurdein** [xarblu/xarblu-overlay#323]
Hi, I use your overlay. I found this small issue, which I temporarily fix by masking but I cannot provide a pull request because when build systems and git comes into play I lose all computer knowledge. I don't know how severe is this, sounds easy but I'm an outsider, I know nothing. I'll provide what Portage blarps in my face:

`gaurdein@gpc# emerge svt-av1                        
Unavailable repository 'nest' referenced by masters entry in '/var/db/repos/nitratesky/metadata/layout.conf'
Calculating dependencies... done!
Dependency resolution took 4.29 s (backtrack: 0/20).

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) media-libs/svt-av1-1.8.0::xarblu-overlay
>>> Downloading 'http://distfiles.gentoo.org/distfiles/00/SVT-AV1-v1.8.0.tar.bz2'
--2024-03-08 23:26:11--  http://distfiles.gentoo.org/distfiles/00/SVT-AV1-v1.8.0.tar.bz2
Resolving distfiles.gentoo.org... 156.146.33.137, 156.146.33.141, 195.181.175.40, ...
Connecting to distfiles.gentoo.org|156.146.33.137|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-03-08 23:26:12 ERROR 404: Not Found.

>>> Downloading 'https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v1.8.0/SVT-AV1-v1.8.0.tar.bz2'
--2024-03-08 23:26:12--  https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v1.8.0/SVT-AV1-v1.8.0.tar.bz2
Resolving gitlab.com... 172.65.251.78, 2606:4700:90:0:f22e:fbec:5bed:a9b9
Connecting to gitlab.com|172.65.251.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘/var/cache/distfiles/SVT-AV1-v1.8.0.tar.bz2.__download__’

/var/cache/distfile     [  <=>               ]   9,14M  34,5MB/s    in 0,3s    

2024-03-08 23:26:12 (34,5 MB/s) - ‘/var/cache/distfiles/SVT-AV1-v1.8.0.tar.bz2.__download__’ saved [9585789]

!!! Fetched file: SVT-AV1-v1.8.0.tar.bz2 VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      9585789
!!! Expected: 9586152
Refetching... File renamed to '/var/cache/distfiles/SVT-AV1-v1.8.0.tar.bz2._checksum_failure_.5ld1ss_k'

!!! Couldn't download 'SVT-AV1-v1.8.0.tar.bz2'. Aborting.

>>> Failed to emerge media-libs/svt-av1-1.8.0, Log file:

>>>  '/var/tmp/portage/media-libs/svt-av1-1.8.0/temp/build.log'`

Thanks for looking at it, and even more thanks if you fix it. Have a nice day!

**Comment by xarblu** [comment]
Hm... not sure how that happened. Probably `pkgdev` using a already downloaded broken archive from distfiles. Now the Manifest should be fixed (the size at least matches your report now).

Anyways thanks for the report!
